apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-apiimg-ci
spec:
  pipelineRef:
    name: pipeline-apiimg-ci
  #serviceAccountName: pipeline
  workspaces:
  - name: workspace-git
    #emptyDir: {}
    #persistentVolumeClaim:
    #  claimName: workspace-git
    volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
          storageClassName: "crc-csi-hostpath-provisioner"
          volumeMode: Filesystem
    
  params:
  - name: repo-url
    value: https://github.com/Carlos-ZRM/3scale_poc.git
  - name: revision
    value: python-api-img
  - name: img-registry
    value: quay.io/rh-ee-creyesma/python-img-api:tekton
  - name: img-context
    value: apiPythonImg

