apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "local-storage"
  volumeMode: Filesystem  # If you want to use it as a filesystem
